name: Deloy netlify ci

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node-version }}
            uses: actions/setup-node@v3 # was "v2" before
            with:
              node-version: ${{ matrix.node-version }}

      - name: Deploy Netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
        # run: curl -X POST -d {} https://api.netlify.com/build_hooks/6615dd8d8beb0f5fe55f5b1e
