name: Deploy Render API CI/CD #Name jobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  #pull_request:
  # branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3 # was "v2" before
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # was "v2" before
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install Dependencies
        run: npm install

      - name: NPM build
        run: npm run

      - name: NPM test
        run: npm test

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  # Deploy jobs render.com
  deploy-sender:
    name: Deploy-Sender
    needs: [build] # Our build must pass in order to run the deploy job
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Sender
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings

  # Deploy jobs netlify
  deploy-netlify:
    name: Deploy-Netlify
    needs: [build] # Our build must pass in order to run the deploy job
    runs-on: ubuntu-latest

    steps:
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
